### ISSUE TITLE
Convert english char to persian char

### ISSUE THREAD

**Issue by rotexhawk** [usablica/persian.js#34]
Great job on this tool. Are there any plans to convert the english characters to Farsi equivalent ? 
Maybe this method can be expanded to detect the language and convert appropriately. 

persianJs("sghl").switchKey().toString()  //   سلام

**Comment by afshinm** [comment]
Hi @rotexhawk 

Well, I don't have enough time to maintain this project at the moment but I appreciate any PRs and I can review it.
