### ISSUE TITLE
Aambiguation in `Readme` file

### ISSUE THREAD

**Issue by mhsattarian** [usablica/persian.js#46]
First of all, thank you for this useful library,
there is a little ambiguation in `Readme` file.

in `Functions` section number 5 is "Convert to English numbers from Arabic and Persian Number" while number 2 has already mentioned, "Convert to English numbers from Persian Number". so mentioning the Persian Number is not necessary again.
also, in GitHub page, the output for number 2 is in Persian.

**Comment by TheYahya** [comment]
Hi @mhsattarian 
Thanks for reporting this bugs.
