### ISSUE TITLE
Can not compare persian words

### ISSUE THREAD

**Issue by soorena110** [usablica/persian.js#52]
سلام دوست عزیز ...
شما لایبرری خیلی خوبی دارید، من که خیلی دوست داشتم، و دوست داشتم همکاری کنم باهاتون تا بتونیم لایبرری رو حتی بهترش هم کنیم.
یه مساله که خیلی دوست داشتم تو لایبرری شما میبود، مقایسه ی کلمات فارسی هست که تقریبا میشه گفت نیاز میشه برای
sort
و..
ممنون میشم اگه اضافه بشه ... البته اینو هم بگم که کد آماده ش رو دارم اگه بخواین اضافه کنید.

**Comment by TheYahya** [comment]
Hi @soorena110 
PRs always appreciated :+1:
